import os
from datetime import datetime

try:
    from pymongo import ASCENDING, DESCENDING, MongoClient
    from pymongo.errors import PyMongoError
except ModuleNotFoundError:
    ASCENDING = 1
    DESCENDING = -1
    MongoClient = None
    PyMongoError = Exception


MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = os.getenv("LOG_PIPELINE_DB_NAME", "log_pipeline")

_client = None
_db = None
_indexes_ready = False


def _get_db():
    global _client, _db

    if MongoClient is None:
        raise RuntimeError("pymongo is not installed")

    if _db is None:
        _client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=2000)
        _db = _client[DB_NAME]

    return _db


def _get_collection(name: str):
    return _get_db()[name]


def create_indexes():
    """
    Create indexes to speed up queries and analytics.
    """

    global _indexes_ready

    if _indexes_ready:
        return

    logs_collection = _get_collection("logs_parsed")

    logs_collection.create_index([("timestamp", DESCENDING)])
    logs_collection.create_index([("level", ASCENDING)])
    logs_collection.create_index([("source_type", ASCENDING)])
    logs_collection.create_index([("service", ASCENDING)])
    logs_collection.create_index([("component", ASCENDING)])
    logs_collection.create_index([("severity_score", DESCENDING)])

    _indexes_ready = True


def insert_log(log: dict):
    """
    Insert a single parsed log document.
    """

    if not log:
        return

    if MongoClient is None:
        return

    create_indexes()
    _get_collection("logs_parsed").insert_one(log)


def insert_logs_bulk(logs: list):
    """
    Insert multiple logs efficiently.
    """

    if not logs:
        return

    if MongoClient is None:
        return

    create_indexes()
    _get_collection("logs_parsed").insert_many(logs)


def insert_alert(alert: dict):
    """
    Insert an alert generated by the alert engine.
    """

    if MongoClient is None:
        return

    alert["triggered_at"] = datetime.utcnow()
    _get_collection("alerts").insert_one(alert)


def get_recent_logs(limit=50):
    """
    Fetch most recent logs.
    """

    if MongoClient is None:
        return []

    return list(
        _get_collection("logs_parsed")
        .find()
        .sort("timestamp", DESCENDING)
        .limit(limit)
    )


def get_error_logs(limit=100):
    """
    Fetch recent ERROR and CRITICAL logs.
    """

    if MongoClient is None:
        return []

    return list(
        _get_collection("logs_parsed")
        .find({"level": {"$in": ["ERROR", "CRITICAL"]}})
        .sort("timestamp", DESCENDING)
        .limit(limit)
    )


def get_log_stats():
    """
    Aggregation for dashboard statistics.
    """

    if MongoClient is None:
        return []

    pipeline = [
        {
            "$group": {
                "_id": "$level",
                "count": {"$sum": 1}
            }
        }
    ]

    return list(_get_collection("logs_parsed").aggregate(pipeline))


def check_connection():
    """
    Verify database connection.
    """

    try:
        if MongoClient is None:
            return False
        _get_db().client.admin.command("ping")
        return True
    except PyMongoError:
        return False
